#!/bin/bash

cd /nexus
mvn clean install -Dmaven.test.skip=true
mkdir target
unzip -d target assemblies/nexus-base-template/target/nexus-base-template-*.zip
cd target
mv nexus-* nexus-3.9.0-01
tar cvzf nexus-3.9.0-01-unix.tar.gz *
mv *.tar.gz /target
